### ISSUE TITLE
Possibly missing setup instructions?

### ISSUE THREAD

**Issue by rwaldron** [keithpops/jeoparty#3]
Hi! I was really excited to build this project, but have run into several issues and was hoping you'd be up for helping me out :)

Following the logical order of JS app install and execution operations...

(with node.js 4.2.1)

1. cloned locally
2. npm install'ed for the clone (this looks successful)
3. `npm run build`
  - Lot's of eslint errors :(
  - Regardless of those errors, something was created—awesome!
4. `npm run start`

```
 npm run start

> web-react@1.1.0 start /Users/rwaldron/clonez/jeoparty
> node dist/server.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open './server/key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/rwaldron/clonez/jeoparty/dist/server.js:100:28)
    at Object.<anonymous> (/Users/rwaldron/clonez/jeoparty/dist/server.js:267:28)
    at Object.<anonymous> (/Users/rwaldron/clonez/jeoparty/dist/server.js:268:31)
    at __webpack_require__ (/Users/rwaldron/clonez/jeoparty/dist/server.js:21:30)
    at Object.<anonymous> (/Users/rwaldron/clonez/jeoparty/dist/server.js:48:19)
    at __webpack_require__ (/Users/rwaldron/clonez/jeoparty/dist/server.js:21:30)
    at /Users/rwaldron/clonez/jeoparty/dist/server.js:41:18

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! web-react@1.1.0 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-react@1.1.0 start script 'node dist/server.js'.
npm ERR! This is most likely a problem with the web-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rwaldron/clonez/jeoparty/npm-debug.log
```

No reason to include the npm-debug.log because the error shown above is straight forward. Any idea why this isn't being created? Can this app run on regular http?

**Comment by rwaldron** [comment]
Maybe all that's needed is additional instructions for setting up the self signed certificates?

**Comment by rwaldron** [comment]
Here's what happened... 

- I generated self signed certs in `/server/`, this allowed me to run the app, but it failed to run correctly (jsservice.io didn't like receiving an https request)
- I "hacked" it back to http and ta-da, everything worked (even the microphone access, which doesn't really follow this: https://github.com/keithpops/jeoparty/commit/1648400cc3d636f8023d22fc3a5c5bbb2c2573a0) (Also, I demo'ed this for my wife and we totally love it!)

**Comment by keithpops** [comment]
@rwaldron Hello! I didn't anticipate the `johnny-five` master chiming in here!

The docs are very much a work-in-progress at the moment. I'm working to have all sorts of material (especially a lot of optimization advice given to me at the conference) setup around this within the next week or so. Hang tight!

As for the SSL stuff, that was a `soul-crushing`, last-minute hack to get the permissions to save properly in Chromium. I didn't want Chromium to constantly alert players about needing permission to access the microphone. For one reason or another, this wasn't an issue when developing on my laptop. Once it went to the Pi, it caused an endless loop which I *might* attribute to components constantly trying to mount without proper permission. When I looked further into the issue or just manually configuring Chromium to just allow it, SSL and generating certificates seemed like a safe fallback, albeit a little too much configuration for my taste. I'm definitely looking into this issue a little further to find some workarounds that don't feel as hacky.

I've added some of these things to a todo in the readme so I'll keep this issue open until I can suss out some of the setup a little better.

**Comment by rwaldron** [comment]
Thanks a ton for taking time to explain this :)
